---
title: "A replication of Coulson & Williams (2005)"
output: rticles::plos_article
---

```{r Load Libraries, include=FALSE}
library(dplyr)
library(jsonlite)
library(readr)
library(stringr)
library(ggplot2)
library(tidyr)
```


# Methods

# Results

## Behavioral

```{r Load Behavioral Data, include=FALSE}
json.files <- list.files(path="data/behavioral/raw", pattern=".json", full.names = TRUE)
behavioral.data <- lapply(json.files, fromJSON) %>% bind_rows()
```

```{r Load merged naming data, include=FALSE}
naming.data <- read_csv('data/behavioral/generated/delayed_naming.csv')
```

### Delayed Naming Task

```{r Compute Delayed Naming Accuracy, include=FALSE}
delayed.naming.subject.data <- naming.data %>%
  group_by(subject_id, left_or_right, sentence_type) %>%
  summarize(m.subject = mean(correct))

delayed.naming.data <- delayed.naming.subject.data %>%
  group_by(left_or_right, sentence_type) %>%
  summarize(m = mean(m.subject), se=sd(m.subject) / sqrt(n()))
```

```{r Plot Delayed Naming Accuracy, echo=FALSE}
ggplot(delayed.naming.data, aes(x=sentence_type, y=m, ymin=m-se, ymax=m+se, color=left_or_right))+
  geom_pointrange(position= position_dodge(width=0.25))+
  labs(x="Sentence Type", y="Proportion Correct", color="Visual Field")+
  theme_bw()
```
### Comprehension Task

```{r Filter comprehension task data, include=FALSE}
comprehension.data <- behavioral.data %>%
  filter(task=="test-response") %>%
  select(subject_id, response, correct_response, correct, left_or_right, sentence_type)
```

```{r Subject-level comprehension data, include=FALSE}
comprehension.subject.data <- comprehension.data %>%
  group_by(subject_id, left_or_right, sentence_type) %>%
  summarize(m.subject = mean(correct))
```

```{r Group-level comprehension data, include=FALSE}
comprehension.summary <- comprehension.subject.data %>%
  group_by(left_or_right, sentence_type) %>%
  summarize(m = mean(m.subject), se=sd(m.subject)/sqrt(n()))
```

```{r Plot group-level comprehension data, echo=FALSE}
ggplot(comprehension.summary, aes(x=sentence_type, y=m, ymin=m-se, ymax=m+se, color=left_or_right))+
  geom_pointrange(position= position_dodge(width=0.25))+
  labs(x="Sentence Type", y="Proportion Correct", color="Visual Field")+
  theme_bw()
```

## EEG

```{r Load EEG data, include=FALSE}
eeg.data <- readRDS("data/eeg/epochs/epochs.rds")

eeg.data <- eeg.data %>%
  filter(event_type %in% 1:6) %>%
  mutate(ending = case_when(
    event_type %in% c(1,4) ~ "filler",
    event_type %in% c(2,5) ~ "joke",
    event_type %in% c(3,6) ~ "nonjoke"
  )) %>%
  mutate(visual_field = case_when(
    event_type %in% c(1,2,3,7) ~ "left",
    event_type %in% c(4,5,6,8) ~ "right"
  ))
```

```{r Remove trials with failed delayed naming, include=FALSE}
naming.correct <- naming.data %>%
  mutate(subject=subject_id) %>%
  select(subject, trial, correct) 

eeg.data.filtered <- eeg.data %>%
  group_by(subject) %>%
  mutate(trial = event_id - min(event_id) + 1) %>%
  ungroup() %>%
  left_join(naming.correct, by=c("subject", "trial")) %>%
  filter(correct==1)
```

### N1

```{r N1 data, include=FALSE}
n1.data <- eeg.data.filtered %>%
  filter(electrode %in% c("P7", "P8", "O1", "O2")) %>%
  filter(ending != "practice") %>%
  mutate(hemisphere = if_else(electrode %in% c("P7", "O1"), "left", "right"))
```

```{r N1 ERPs, include=FALSE}
n1.erps <- n1.data %>%
  filter(good_segment == TRUE) %>%
  group_by(subject, electrode, visual_field, t) %>%
  summarize(mean.v = mean(v))

n1.erps.grand.average <- n1.erps %>%
  group_by(electrode, visual_field, t) %>%
  summarize(m = mean(mean.v), se=sd(mean.v)/sqrt(n()))
```

```{r Plot N1 ERPs, echo=FALSE}
ggplot(n1.erps.grand.average, aes(x=t, y=m, ymin=m-se, ymax=m+se, color=visual_field, fill=visual_field))+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_ribbon(color=NA, alpha=0.2)+
  geom_line(size=0.8)+
  #coord_cartesian(xlim=c(-100,500))+
  facet_wrap(~electrode)+
  theme_minimal()+
  theme(panel.grid = element_blank())
```

### N400

```{r Filter N400 data, include=FALSE}
n4.data <- eeg.data.filtered %>%
  filter(electrode %in% c("P3", "P4", "Pz")) %>%
  filter(ending != "practice")
```

```{r Subject N400 ERPs, include=FALSE}
n4.erps <- n4.data %>%
  filter(good_segment == TRUE) %>%
  group_by(subject, ending, visual_field, t) %>%
  summarize(mean.v = mean(v))
```

```{r Grand Average N400 ERPs, include=FALSE}
n4.erps.grand.average <- n4.erps %>%
  group_by(ending, visual_field, t) %>%
  summarize(m = mean(mean.v), se=sd(mean.v) / sqrt(n()))
```

```{r Plot N400 ERP, echo=FALSE}
ggplot(n4.erps.grand.average, aes(x=t, y=m, ymin=m-se, ymax=m+se, color=ending, fill=ending))+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_ribbon(color=NA, alpha=0.2)+
  geom_line(size=0.8)+
  #coord_cartesian(xlim=c(-100,500))+
  facet_wrap(~visual_field)+
  theme_minimal()+
  theme(panel.grid = element_blank())
```

```{r Calculate N400 difference waves, include=FALSE}
n4.difference.waves <- n4.erps %>%
  pivot_wider(names_from = ending, values_from = mean.v) %>%
  mutate(joke.filler.diff = joke - filler) %>%
  mutate(nonjoke.filler.diff = nonjoke - filler) %>%
  select(-joke, -filler, -nonjoke) %>%
  pivot_longer(c('joke.filler.diff', 'nonjoke.filler.diff'), names_to = "ending", values_to = "diff.v")
```

```{r Calculate grand average N400 difference waves, include=FALSE}
n4.difference.waves.grand.average <- n4.difference.waves %>%
  group_by(ending, visual_field, t) %>%
  summarize(m = mean(diff.v), se=sd(diff.v) / sqrt(n()))
```

```{r Plot Difference Waves N400, echo=FALSE}
ggplot(n4.difference.waves.grand.average, aes(x=t, y=m, ymin=m-se, ymax=m+se, color=ending, fill=ending))+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_ribbon(color=NA, alpha=0.2)+
  geom_line(size=0.8)+
  #coord_cartesian(xlim=c(-100,500))+
  facet_wrap(~visual_field)+
  theme_minimal()+
  theme(panel.grid = element_blank())
```